// Mocks generated by Mockito 5.0.10 from annotations
// in lezato/test/restaurant_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:resto_app/provider/restaurant_provider.dart' as _i2;
import 'package:resto_app/service/api_service.dart' as _i3;

class MockRestaurantProvider extends _i1.Mock
    implements _i2.RestaurantProvider {
  MockRestaurantProvider() {
    _i1.throwOnMissingStub(this);
  }
}

class MockApiService extends _i1.Mock implements _i3.Apiservice {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }
}
